### ISSUE TITLE
Initiate  package review request 

### ISSUE THREAD

**Issue by ansarusc** [UBC-MDS/aRidanalysis#52]

**Comment by CraigEnsemble** [comment]
Adding template here, will fill in with another comment below as a draft

---
name: Submit software for review
about: Use this template to submit software for review

---


Submitting Author: Name (@github_handle)
Other Authors: (delete if none) Name (@github_handle)
Repository:
Version submitted:
Editor:  TBD 
Reviewers:  TBD 

Archive: TBD
Version accepted: TBD

---



-   Paste the full DESCRIPTION file inside a code block below:

```

```


## Scope

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below. If you are unsure, we suggest you make a pre-submission inquiry.):

	- [ ] data retrieval
	- [ ] data extraction
	- [ ] data munging
	- [ ] data deposition
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis

- Explain how and why the package falls under these categories (briefly, 1-2 sentences):


-   Who is the target audience and what are scientific applications of this package?

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

-   If you made a pre-submission enquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

## Technical checks

Confirm each of the following by checking the box.

- [ ] I have read the [guide for authors](https://devguide.ropensci.org/guide-for-authors.html) and [rOpenSci packaging guide](https://devguide.ropensci.org/building.html).

This package:

- [ ] does not violate the Terms of Service of any service it interacts with.
- [ ] has a CRAN and OSI accepted license.
- [ ] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme).
- [ ] includes [documentation with examples for all functions, created with roxygen2](https://ropensci.github.io/dev_guide/building.html#documentation).
- [ ] contains a vignette with examples of its essential functions and uses.
- [ ] has a [test suite](https://ropensci.github.io/dev_guide/building.html#testing).
- [ ] has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage using services such as Travis CI, Coveralls and/or CodeCov.

## Publication options

- [ ] Do you intend for this package to go on CRAN?
- [ ] Do you intend for this package to go on Bioconductor?

- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:

<details>
<summary>MEE Options</summary>

- [ ] The package is novel and will be of interest to the broad readership of the journal.
- [ ] The manuscript describing the package is no longer than 3000 words.
- [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
- (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no guarantee that your manuscript will be within MEE scope.*)
- (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

</details>

## Code of conduct

- [ ] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.github.io/dev_guide/policies.html#code-of-conduct) during the review process and in maintaining my package should it be accepted.

**Comment by cmmclaug** [comment]
Submitting Authors: 
* Santiago Rugeles (@ansarusc)
* Neel Phaterpekar (@nphaterp)  
* Daniel Ortiz (@danielon-5)  
* Craig McLaughlin (@cmmclaug)  

Repository: https://github.com/UBC-MDS/aRidanalysis
Version submitted: 0.3.0
Editor: Tiffany Timbers (@ttimbers)
Reviewers:  TBD 

Archive: TBD
Version accepted: TBD

---



DESCRIPTION:

```
Package: aRidanalysis
Title: DRY out your regression analysis!
Version: 0.3.0
Authors@R: 
    person(given = "Santiago",
           family = "Rugeles Schoonewolff",
           role = c("aut", "cre"),
           email = "nphaterp@ualberta.ca")
    person(given = "Daniel",
           family = "Ortiz Nunez",
           role = c("aut", "cre"),
           email = "daniel.ortiz.n@gmail.com")
    person(given = "Neel",
           family = "Phaterpekar",
           role = c("aut", "cre"),
           email = "nphaterp@ualberta.ca")
    person(given = "Craig",
           family = "McLaughlin",
           role = c("aut", "cre"),
           email = "cswag7@student.ubc.ca")
Description: The aRidanalysis package allows users to streamline their regression analysis by providing functions that return model objects with familiar sklearn interfaces. An EDA function and model functions for different regression analysis response types are provided to simplify the analysis and modelling process and reduce code duplication. These model objects will allow users to leverage the inference capabilities of the R ecosystem with the prediction pipelines familiar in Python.
License: MIT + file LICENSE
Encoding: UTF-8
LazyData: true
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.1.1
Imports: 
    dplyr,
    tidyr,
    glmnet,
    palmerpenguins,
    ggplot2,
    GGally,
    tidyverse,
    MASS,
    broom,
    AER,
    tibble,
    rlang,
    stringr,
    magrittr
Suggests: 
    testthat (>= 3.0.0)
Config/testthat/edition: 3

```


## Scope

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below. If you are unsure, we suggest you make a pre-submission inquiry.):

	- [ ] data retrieval
	- [ ] data extraction
	- [x] data munging
	- [ ] data deposition
	- [x] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis

- Explain how and why the package falls under these categories (briefly, 1-2 sentences):
        - This aRidanalysis package falls under data munging because we provide functions to perform exploratory data and instantiate regression analysis models on provided data.
        - This aRidanalysis package falls under workflow automation given the provided function interfaces simplify and logically translate the inputs to other libraries to streamline the generation of visualizations and models.

-   Who is the target audience and what are scientific applications of this package?
        - The target audience is newer machine learning enthusiasts familiar with the Sci-kit Learn Python interfaces looking to streamline their machine learning workflows in the R language.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?
        - Yes, the [superml](https://cran.r-project.org/web/packages/superml/vignettes/introduction.html) package essentially implements almost the entire scope of the Ski-kit Learn functionality. Our package is much more focused, with a much simpler interface not requiring the parsing of a huge volume and range of functionality.

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?
        - Yes, this package is focused on very general data regression analysis.

-   If you made a pre-submission enquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

## Technical checks

Confirm each of the following by checking the box.

- [ x] I have read the [guide for authors](https://devguide.ropensci.org/guide-for-authors.html) and [rOpenSci packaging guide](https://devguide.ropensci.org/building.html).

This package:

- [x] does not violate the Terms of Service of any service it interacts with.
- [x] has a CRAN and OSI accepted license.
- [x] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme).
- [x] includes [documentation with examples for all functions, created with roxygen2](https://ropensci.github.io/dev_guide/building.html#documentation).
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a [test suite](https://ropensci.github.io/dev_guide/building.html#testing).
- [x] has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage using services such as Travis CI, Coveralls and/or CodeCov.

## Publication options

- [ ] Do you intend for this package to go on CRAN?
- [ ] Do you intend for this package to go on Bioconductor?

- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:

<details>
<summary>MEE Options</summary>

- [ ] The package is novel and will be of interest to the broad readership of the journal.
- [ ] The manuscript describing the package is no longer than 3000 words.
- [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
- (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no guarantee that your manuscript will be within MEE scope.*)
- (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

</details>

## Code of conduct

- [x] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.github.io/dev_guide/policies.html#code-of-conduct) during the review process and in maintaining my package should it be accepted.

**Comment by cmmclaug** [comment]
Request initiated: https://github.com/UBC-MDS/software-review-2021/issues/35
